import { Pool, type PoolClient, type QueryResultRow, types } from "pg";
import { CURATED_GRAMMAR_POINTS } from "./grammar-seed";
import { REGISTER_SEED } from "./register-seed";
import { COLLOCATION_SEED } from "./collocation-seed";
import { CHARACTER_BREAKDOWN_SEED } from "./character-breakdown-seed";

types.setTypeParser(types.builtins.INT8, (value) => Number(value));
types.setTypeParser(types.builtins.NUMERIC, (value) => Number(value));
types.setTypeParser(types.builtins.TIMESTAMP, (value) =>
  new Date(`${value}Z`).toISOString()
);
types.setTypeParser(types.builtins.TIMESTAMPTZ, (value) =>
  new Date(value).toISOString()
);

declare global {
  var __hanzibitPool: Pool | undefined;
  var __hanzibitSchemaInit: Promise<void> | undefined;
  var __hanzibitSchemaVersion: number | undefined;
}

const SCHEMA_VERSION = 37;

const APP_SCHEMA_SQL = `
  CREATE TABLE IF NOT EXISTS "user" (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    "emailVerified" BOOLEAN NOT NULL DEFAULT FALSE,
    image TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS session (
    id TEXT PRIMARY KEY,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    token TEXT NOT NULL UNIQUE,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
  );

  CREATE TABLE IF NOT EXISTS account (
    id TEXT PRIMARY KEY,
    "accountId" TEXT NOT NULL,
    "providerId" TEXT NOT NULL,
    "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    "accessToken" TEXT,
    "refreshToken" TEXT,
    "idToken" TEXT,
    "accessTokenExpiresAt" TIMESTAMPTZ,
    "refreshTokenExpiresAt" TIMESTAMPTZ,
    scope TEXT,
    password TEXT,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS verification (
    id TEXT PRIMARY KEY,
    identifier TEXT NOT NULL,
    value TEXT NOT NULL,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "createdAt" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS journal_entries (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    title_zh TEXT NOT NULL,
    title_en TEXT NOT NULL,
    unit TEXT,
    hsk_level INTEGER DEFAULT 1,
    content_zh TEXT NOT NULL,
    bookmarked INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS entry_annotations (
    id TEXT PRIMARY KEY,
    entry_id TEXT NOT NULL REFERENCES journal_entries(id) ON DELETE CASCADE,
    type TEXT NOT NULL CHECK(type IN ('grammar_tip', 'mnemonic')),
    title TEXT NOT NULL,
    content TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS vocabulary (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    character_zh TEXT NOT NULL,
    pinyin TEXT NOT NULL,
    meaning TEXT NOT NULL,
    hsk_level INTEGER DEFAULT 1,
    category TEXT DEFAULT 'general',
    mastery INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_reviewed TIMESTAMPTZ
  );

  CREATE TABLE IF NOT EXISTS grammar_points (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    pattern TEXT,
    explanation TEXT NOT NULL,
    examples TEXT NOT NULL DEFAULT '[]',
    hsk_level INTEGER DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS flashcards (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    front TEXT NOT NULL,
    back TEXT NOT NULL,
    deck TEXT DEFAULT 'general',
    next_review TIMESTAMPTZ DEFAULT NOW(),
    interval_days INTEGER DEFAULT 1,
    ease_factor DOUBLE PRECISION DEFAULT 2.5,
    review_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    source_entry_id TEXT
  );

  CREATE TABLE IF NOT EXISTS lessons (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    unit TEXT NOT NULL,
    hsk_level INTEGER DEFAULT 1,
    description TEXT,
    content TEXT NOT NULL DEFAULT '',
    sort_order INTEGER DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS review_history (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    item_type TEXT NOT NULL CHECK(item_type IN ('vocabulary', 'flashcard', 'grammar')),
    item_id TEXT NOT NULL,
    item_label TEXT NOT NULL,
    score INTEGER CHECK(score BETWEEN 1 AND 5),
    reviewed_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS hsk_words (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    simplified TEXT NOT NULL,
    traditional TEXT,
    pinyin TEXT NOT NULL,
    english TEXT NOT NULL,
    hsk_level INTEGER NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_hsk_simplified ON hsk_words(simplified);
  CREATE INDEX IF NOT EXISTS idx_hsk_level ON hsk_words(hsk_level);

  CREATE TABLE IF NOT EXISTS cedict_entries (
    simplified TEXT NOT NULL,
    traditional TEXT NOT NULL,
    pinyin TEXT NOT NULL,
    pinyin_display TEXT NOT NULL,
    english TEXT NOT NULL,
    char_count INTEGER NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_cedict_simplified ON cedict_entries(simplified);

  CREATE TABLE IF NOT EXISTS gloss_cache (
    entry_id TEXT PRIMARY KEY,
    content_hash TEXT NOT NULL,
    gloss_json TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE TABLE IF NOT EXISTS subscriptions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL UNIQUE,
    stripe_customer_id TEXT NOT NULL,
    stripe_subscription_id TEXT,
    plan TEXT NOT NULL DEFAULT 'free' CHECK(plan IN ('free', 'pro')),
    status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active', 'trialing', 'past_due', 'canceled', 'unpaid', 'incomplete')),
    current_period_end TIMESTAMPTZ,
    cancel_at_period_end INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_sub_user ON subscriptions(user_id);
  CREATE INDEX IF NOT EXISTS idx_sub_stripe_customer ON subscriptions(stripe_customer_id);

  CREATE TABLE IF NOT EXISTS user_roles (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('teacher')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, role)
  );

  CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON user_roles(user_id);

  CREATE TABLE IF NOT EXISTS classrooms (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    join_code TEXT NOT NULL UNIQUE,
    is_private_tutoring INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_classrooms_teacher ON classrooms(teacher_user_id);
  CREATE INDEX IF NOT EXISTS idx_classrooms_join_code ON classrooms(join_code);

  CREATE TABLE IF NOT EXISTS classroom_members (
    id TEXT PRIMARY KEY,
    classroom_id TEXT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('teacher', 'student')),
    joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(classroom_id, user_id)
  );

  CREATE INDEX IF NOT EXISTS idx_classroom_members_user ON classroom_members(user_id);
  CREATE INDEX IF NOT EXISTS idx_classroom_members_classroom ON classroom_members(classroom_id);

  CREATE TABLE IF NOT EXISTS assignments (
    id TEXT PRIMARY KEY,
    classroom_id TEXT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
    created_by_user_id TEXT NOT NULL,
    type TEXT NOT NULL CHECK(type IN ('journal_prompt', 'study_guide_word', 'study_guide_level', 'reading_response')),
    title TEXT NOT NULL,
    description TEXT,
    prompt TEXT,
    hsk_level INTEGER,
    source_ref TEXT,
    allow_resubmission INTEGER NOT NULL DEFAULT 1,
    due_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_assignments_classroom_created
    ON assignments(classroom_id, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_assignments_classroom_due
    ON assignments(classroom_id, due_at);

  CREATE TABLE IF NOT EXISTS teacher_resources (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL,
    resource_type TEXT NOT NULL CHECK(resource_type IN ('journal_prompt', 'study_word_set', 'study_level_set', 'reading_response', 'grammar_note')),
    title TEXT NOT NULL,
    description TEXT,
    hsk_level INTEGER,
    source_assignment_id TEXT,
    archived INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_teacher_resources_teacher
    ON teacher_resources(teacher_user_id, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_teacher_resources_type
    ON teacher_resources(teacher_user_id, resource_type, archived);

  CREATE TABLE IF NOT EXISTS teacher_resource_items (
    id TEXT PRIMARY KEY,
    resource_id TEXT NOT NULL REFERENCES teacher_resources(id) ON DELETE CASCADE,
    item_type TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    content_json JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_teacher_resource_items_resource
    ON teacher_resource_items(resource_id, sort_order, created_at);

  CREATE TABLE IF NOT EXISTS assignment_templates (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL,
    resource_id TEXT REFERENCES teacher_resources(id) ON DELETE SET NULL,
    template_type TEXT NOT NULL CHECK(template_type IN ('journal_prompt', 'study_guide_word', 'study_guide_level', 'reading_response')),
    title TEXT NOT NULL,
    description TEXT,
    prompt TEXT,
    hsk_level INTEGER,
    source_ref TEXT,
    allow_resubmission INTEGER NOT NULL DEFAULT 1,
    archived INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_assignment_templates_teacher
    ON assignment_templates(teacher_user_id, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_assignment_templates_resource
    ON assignment_templates(resource_id);

  CREATE TABLE IF NOT EXISTS teacher_strategies (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    issue_focus TEXT,
    goal_focus TEXT,
    guidance TEXT,
    refinement_note TEXT,
    last_refined_at TIMESTAMPTZ,
    linked_template_id TEXT REFERENCES assignment_templates(id) ON DELETE SET NULL,
    linked_resource_id TEXT REFERENCES teacher_resources(id) ON DELETE SET NULL,
    usage_count INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_teacher_strategies_teacher
    ON teacher_strategies(teacher_user_id, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_teacher_strategies_focus
    ON teacher_strategies(teacher_user_id, archived, updated_at DESC);

  CREATE TABLE IF NOT EXISTS teacher_playbooks (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    summary TEXT NOT NULL,
    issue_focus TEXT,
    goal_focus TEXT,
    when_to_use TEXT,
    guidance TEXT,
    linked_template_id TEXT REFERENCES assignment_templates(id) ON DELETE SET NULL,
    linked_resource_id TEXT REFERENCES teacher_resources(id) ON DELETE SET NULL,
    refinement_note TEXT,
    last_refined_at TIMESTAMPTZ,
    replacement_playbook_id TEXT REFERENCES teacher_playbooks(id) ON DELETE SET NULL,
    usage_count INTEGER NOT NULL DEFAULT 0,
    archived INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_teacher_playbooks_teacher
    ON teacher_playbooks(teacher_user_id, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_teacher_playbooks_focus
    ON teacher_playbooks(teacher_user_id, archived, updated_at DESC);

  CREATE TABLE IF NOT EXISTS teacher_playbook_strategies (
    id TEXT PRIMARY KEY,
    playbook_id TEXT NOT NULL REFERENCES teacher_playbooks(id) ON DELETE CASCADE,
    strategy_id TEXT NOT NULL REFERENCES teacher_strategies(id) ON DELETE CASCADE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(playbook_id, strategy_id)
  );

  CREATE INDEX IF NOT EXISTS idx_teacher_playbook_strategies_playbook
    ON teacher_playbook_strategies(playbook_id, sort_order, created_at);
  CREATE INDEX IF NOT EXISTS idx_teacher_playbook_strategies_strategy
    ON teacher_playbook_strategies(strategy_id, created_at);

  CREATE TABLE IF NOT EXISTS private_student_playbook_applications (
    id TEXT PRIMARY KEY,
    private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
    playbook_id TEXT NOT NULL REFERENCES teacher_playbooks(id) ON DELETE CASCADE,
    applied_by_user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    application_note TEXT,
    linked_review_id TEXT REFERENCES private_student_reviews(id) ON DELETE SET NULL,
    linked_lesson_plan_id TEXT REFERENCES private_lesson_plans(id) ON DELETE SET NULL,
    linked_goal_id TEXT REFERENCES private_student_goals(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_private_playbook_apps_private
    ON private_student_playbook_applications(private_student_id, applied_at DESC, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_private_playbook_apps_playbook
    ON private_student_playbook_applications(playbook_id, applied_at DESC, created_at DESC);

  CREATE TABLE IF NOT EXISTS private_student_playbook_outcomes (
    id TEXT PRIMARY KEY,
    playbook_application_id TEXT NOT NULL UNIQUE REFERENCES private_student_playbook_applications(id) ON DELETE CASCADE,
    private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
    teacher_playbook_id TEXT NOT NULL REFERENCES teacher_playbooks(id) ON DELETE CASCADE,
    teacher_user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    outcome_status TEXT NOT NULL CHECK(outcome_status IN ('helped', 'partial', 'no_change', 'replace')),
    outcome_note TEXT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_private_playbook_outcomes_private
    ON private_student_playbook_outcomes(private_student_id, recorded_at DESC, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_private_playbook_outcomes_playbook
    ON private_student_playbook_outcomes(teacher_playbook_id, recorded_at DESC, created_at DESC);

  CREATE TABLE IF NOT EXISTS private_student_strategy_applications (
    id TEXT PRIMARY KEY,
    private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
    teacher_strategy_id TEXT NOT NULL REFERENCES teacher_strategies(id) ON DELETE CASCADE,
    applied_by_user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    application_note TEXT,
    linked_review_id TEXT REFERENCES private_student_reviews(id) ON DELETE SET NULL,
    linked_lesson_plan_id TEXT REFERENCES private_lesson_plans(id) ON DELETE SET NULL,
    linked_goal_id TEXT REFERENCES private_student_goals(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_private_strategy_apps_private
    ON private_student_strategy_applications(private_student_id, applied_at DESC, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_private_strategy_apps_strategy
    ON private_student_strategy_applications(teacher_strategy_id, applied_at DESC, created_at DESC);

  CREATE TABLE IF NOT EXISTS private_student_strategy_outcomes (
    id TEXT PRIMARY KEY,
    strategy_application_id TEXT NOT NULL UNIQUE REFERENCES private_student_strategy_applications(id) ON DELETE CASCADE,
    private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
    teacher_strategy_id TEXT NOT NULL REFERENCES teacher_strategies(id) ON DELETE CASCADE,
    teacher_user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    outcome_status TEXT NOT NULL CHECK(outcome_status IN ('helped', 'partial', 'no_change', 'replace')),
    outcome_note TEXT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_private_strategy_outcomes_private
    ON private_student_strategy_outcomes(private_student_id, recorded_at DESC, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_private_strategy_outcomes_strategy
    ON private_student_strategy_outcomes(teacher_strategy_id, recorded_at DESC, created_at DESC);

  CREATE TABLE IF NOT EXISTS assignment_submissions (
    id TEXT PRIMARY KEY,
    assignment_id TEXT NOT NULL REFERENCES assignments(id) ON DELETE CASCADE,
    student_user_id TEXT NOT NULL,
    journal_entry_id TEXT REFERENCES journal_entries(id) ON DELETE SET NULL,
    status TEXT NOT NULL CHECK(status IN ('not_started', 'draft', 'submitted', 'reviewed')),
    submitted_at TIMESTAMPTZ,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(assignment_id, student_user_id)
  );

  CREATE INDEX IF NOT EXISTS idx_assignment_submissions_student_status
    ON assignment_submissions(student_user_id, status);
  CREATE INDEX IF NOT EXISTS idx_assignment_submissions_assignment_status
    ON assignment_submissions(assignment_id, status);

  CREATE TABLE IF NOT EXISTS submission_feedback (
    id TEXT PRIMARY KEY,
    submission_id TEXT NOT NULL REFERENCES assignment_submissions(id) ON DELETE CASCADE,
    teacher_user_id TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_submission_feedback_submission
    ON submission_feedback(submission_id, created_at DESC);

  CREATE TABLE IF NOT EXISTS referral_codes (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL,
    code TEXT NOT NULL UNIQUE,
    active INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_referral_codes_teacher
    ON referral_codes(teacher_user_id, created_at DESC);

  CREATE TABLE IF NOT EXISTS referral_attributions (
    id TEXT PRIMARY KEY,
    referral_code_id TEXT NOT NULL REFERENCES referral_codes(id) ON DELETE CASCADE,
    teacher_user_id TEXT NOT NULL,
    student_user_id TEXT NOT NULL UNIQUE,
    referral_code TEXT NOT NULL,
    attribution_source TEXT NOT NULL DEFAULT 'referral_link',
    attributed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    converted_at TIMESTAMPTZ,
    stripe_checkout_session_id TEXT,
    stripe_customer_id TEXT,
    stripe_subscription_id TEXT
  );

  CREATE INDEX IF NOT EXISTS idx_referral_attributions_teacher
    ON referral_attributions(teacher_user_id, attributed_at DESC);
  CREATE INDEX IF NOT EXISTS idx_referral_attributions_student
    ON referral_attributions(student_user_id);

  CREATE TABLE IF NOT EXISTS referral_commissions (
    id TEXT PRIMARY KEY,
    attribution_id TEXT NOT NULL REFERENCES referral_attributions(id) ON DELETE CASCADE,
    teacher_user_id TEXT NOT NULL,
    student_user_id TEXT NOT NULL,
    stripe_checkout_session_id TEXT UNIQUE,
    stripe_subscription_id TEXT,
    gross_amount_cents INTEGER NOT NULL,
    commission_rate NUMERIC NOT NULL,
    commission_amount_cents INTEGER NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('pending', 'approved', 'paid', 'reversed')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_referral_commissions_teacher_status
    ON referral_commissions(teacher_user_id, status, created_at DESC);

  CREATE TABLE IF NOT EXISTS teacher_payouts (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL,
    period_label TEXT NOT NULL,
    total_amount_cents INTEGER NOT NULL,
    status TEXT NOT NULL CHECK(status IN ('pending', 'paid')),
    paid_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_teacher_payouts_teacher
    ON teacher_payouts(teacher_user_id, created_at DESC);

  CREATE TABLE IF NOT EXISTS teacher_profiles (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL UNIQUE,
    public_slug TEXT NOT NULL UNIQUE,
    headline TEXT,
    bio TEXT,
    languages_json JSONB NOT NULL DEFAULT '[]',
    specialties_json JSONB NOT NULL DEFAULT '[]',
    levels_json JSONB NOT NULL DEFAULT '[]',
    timezone TEXT,
    pricing_summary TEXT,
    availability_summary TEXT,
    years_experience INTEGER,
    teaching_style TEXT,
    is_public INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_teacher_profiles_public
    ON teacher_profiles(is_public, updated_at DESC);

  CREATE TABLE IF NOT EXISTS teacher_tutoring_settings (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL UNIQUE,
    default_template_id TEXT REFERENCES assignment_templates(id) ON DELETE SET NULL,
    intro_message TEXT,
    default_private_classroom_prefix TEXT,
    cadence_type TEXT,
    target_session_length_minutes INTEGER,
    cadence_notes TEXT,
    format_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_teacher_tutoring_settings_teacher
    ON teacher_tutoring_settings(teacher_user_id);

  CREATE TABLE IF NOT EXISTS teacher_inquiries (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL,
    student_user_id TEXT NOT NULL,
    message TEXT,
    onboarding_message TEXT,
    status TEXT NOT NULL CHECK(status IN ('pending', 'accepted', 'declined', 'converted')),
    created_classroom_id TEXT REFERENCES classrooms(id) ON DELETE SET NULL,
    initial_assignment_id TEXT REFERENCES assignments(id) ON DELETE SET NULL,
    conversion_completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_teacher_inquiries_teacher_status
    ON teacher_inquiries(teacher_user_id, status, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_teacher_inquiries_student_status
    ON teacher_inquiries(student_user_id, status, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_teacher_inquiries_pair
    ON teacher_inquiries(teacher_user_id, student_user_id, created_at DESC);

  CREATE TABLE IF NOT EXISTS private_students (
    id TEXT PRIMARY KEY,
    teacher_user_id TEXT NOT NULL,
    student_user_id TEXT NOT NULL,
    classroom_id TEXT NOT NULL UNIQUE REFERENCES classrooms(id) ON DELETE CASCADE,
    inquiry_id TEXT NOT NULL UNIQUE REFERENCES teacher_inquiries(id) ON DELETE CASCADE,
    status TEXT NOT NULL CHECK(status IN ('onboarding', 'active', 'awaiting_teacher', 'awaiting_student', 'inactive')),
    next_step_type TEXT CHECK(next_step_type IN ('complete_assignment', 'review_feedback', 'await_teacher_assignment', 'follow_up', 'none')),
    next_assignment_id TEXT REFERENCES assignments(id) ON DELETE SET NULL,
    follow_up_note TEXT,
    last_strategy_id TEXT REFERENCES teacher_strategies(id) ON DELETE SET NULL,
    last_strategy_applied_at TIMESTAMPTZ,
    last_playbook_id TEXT REFERENCES teacher_playbooks(id) ON DELETE SET NULL,
    last_playbook_applied_at TIMESTAMPTZ,
    last_review_snapshot_at TIMESTAMPTZ,
    last_plan_adapted_at TIMESTAMPTZ,
    last_teacher_action_at TIMESTAMPTZ,
    last_student_activity_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_private_students_teacher_status
    ON private_students(teacher_user_id, status, updated_at DESC);
  CREATE INDEX IF NOT EXISTS idx_private_students_student
    ON private_students(student_user_id, updated_at DESC);

  CREATE TABLE IF NOT EXISTS private_student_goals (
    id TEXT PRIMARY KEY,
    private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
    teacher_user_id TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT,
    status TEXT NOT NULL CHECK(status IN ('active', 'completed', 'paused')),
    progress_status TEXT CHECK(progress_status IN ('improving', 'stable', 'needs_reinforcement', 'blocked')),
    progress_note TEXT,
    last_progress_at TIMESTAMPTZ,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
  );

  CREATE INDEX IF NOT EXISTS idx_private_student_goals_private_status
    ON private_student_goals(private_student_id, status, sort_order, updated_at DESC);

  CREATE TABLE IF NOT EXISTS private_lesson_history (
    id TEXT PRIMARY KEY,
    private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
    teacher_user_id TEXT NOT NULL,
    classroom_id TEXT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
    lesson_plan_id TEXT REFERENCES private_lesson_plans(id) ON DELETE SET NULL,
    assignment_id TEXT REFERENCES assignments(id) ON DELETE SET NULL,
    summary TEXT NOT NULL,
    practice_focus TEXT,
    issue_tags_json TEXT NOT NULL DEFAULT '[]',
    intervention_note TEXT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_private_lesson_history_private_date
    ON private_lesson_history(private_student_id, recorded_at DESC);
  CREATE INDEX IF NOT EXISTS idx_private_lesson_history_teacher_date
    ON private_lesson_history(teacher_user_id, recorded_at DESC);

  CREATE TABLE IF NOT EXISTS private_student_reviews (
    id TEXT PRIMARY KEY,
    private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
    teacher_user_id TEXT NOT NULL,
    reviewed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    summary TEXT NOT NULL,
    what_improved TEXT,
    what_needs_change TEXT,
    adaptation_note TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_private_student_reviews_private_date
    ON private_student_reviews(private_student_id, reviewed_at DESC, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_private_student_reviews_teacher_date
    ON private_student_reviews(teacher_user_id, reviewed_at DESC, created_at DESC);

  CREATE TABLE IF NOT EXISTS private_lesson_plans (
    id TEXT PRIMARY KEY,
    private_student_id TEXT NOT NULL UNIQUE REFERENCES private_students(id) ON DELETE CASCADE,
    teacher_user_id TEXT NOT NULL,
    classroom_id TEXT NOT NULL REFERENCES classrooms(id) ON DELETE CASCADE,
    next_assignment_id TEXT REFERENCES assignments(id) ON DELETE SET NULL,
    next_template_id TEXT REFERENCES assignment_templates(id) ON DELETE SET NULL,
    plan_status TEXT NOT NULL CHECK(plan_status IN ('planned', 'awaiting_assignment', 'awaiting_completion', 'completed', 'stale')),
    target_date DATE,
    focus_note TEXT,
    before_lesson_expectation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_private_lesson_plans_teacher_status
    ON private_lesson_plans(teacher_user_id, plan_status, updated_at DESC);
  CREATE INDEX IF NOT EXISTS idx_private_lesson_plans_target_date
    ON private_lesson_plans(target_date);

  CREATE TABLE IF NOT EXISTS daily_loop_completions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    completed_on DATE NOT NULL,
    completed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, completed_on)
  );

  CREATE INDEX IF NOT EXISTS idx_daily_loop_user_date
    ON daily_loop_completions(user_id, completed_on DESC);

  CREATE TABLE IF NOT EXISTS tts_cache (
    cache_key  TEXT PRIMARY KEY,
    blob_url   TEXT NOT NULL,
    char_count INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    play_count INTEGER NOT NULL DEFAULT 0
  );

  CREATE TABLE IF NOT EXISTS tts_usage (
    id            TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
    user_id       TEXT REFERENCES "user"(id) ON DELETE SET NULL,
    cache_key     TEXT,
    was_cache_hit BOOLEAN NOT NULL,
    char_count    INTEGER NOT NULL,
    type          TEXT NOT NULL CHECK (type IN ('word','sentence','dynamic')),
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
  );

  CREATE INDEX IF NOT EXISTS idx_tts_usage_user_id ON tts_usage(user_id);
  CREATE INDEX IF NOT EXISTS idx_tts_usage_created_at ON tts_usage(created_at);

  CREATE TABLE IF NOT EXISTS curated_grammar_points (
    id SERIAL PRIMARY KEY,
    hsk_level INTEGER NOT NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    title TEXT NOT NULL,
    pattern TEXT,
    explanation TEXT NOT NULL,
    examples TEXT NOT NULL DEFAULT '[]',
    reading_passage TEXT NOT NULL DEFAULT '',
    comprehension_question TEXT NOT NULL DEFAULT '',
    journal_prompt TEXT NOT NULL DEFAULT '',
    UNIQUE(hsk_level, display_order)
  );

  CREATE INDEX IF NOT EXISTS idx_cgp_level ON curated_grammar_points(hsk_level, display_order);

  CREATE TABLE IF NOT EXISTS user_grammar_progress (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    grammar_point_id INTEGER NOT NULL REFERENCES curated_grammar_points(id) ON DELETE CASCADE,
    studied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, grammar_point_id)
  );

  CREATE INDEX IF NOT EXISTS idx_ugp_user ON user_grammar_progress(user_id, studied_at DESC);

  CREATE TABLE IF NOT EXISTS hsk_collocations (
    id SERIAL PRIMARY KEY,
    word_simplified TEXT NOT NULL,
    sentence_zh TEXT NOT NULL,
    sentence_en TEXT NOT NULL,
    known_words TEXT[] NOT NULL DEFAULT '{}',
    UNIQUE(word_simplified, sentence_zh)
  );

  CREATE INDEX IF NOT EXISTS idx_hsk_collocations_word ON hsk_collocations(word_simplified);

  CREATE TABLE IF NOT EXISTS character_components (
    character TEXT PRIMARY KEY,
    radical TEXT NOT NULL,
    radical_meaning TEXT NOT NULL,
    components_json TEXT NOT NULL,
    mnemonic TEXT
  );
`;

function getDatabaseUrl(): string {
  const connectionString = process.env.DATABASE_URL;
  if (!connectionString) {
    throw new Error("DATABASE_URL is not set. Point it at your Neon Postgres database.");
  }
  return connectionString;
}

export function getPool(): Pool {
  if (!global.__hanzibitPool) {
    global.__hanzibitPool = new Pool({
      connectionString: getDatabaseUrl(),
      ssl: getDatabaseUrl().includes("localhost")
        ? false
        : { rejectUnauthorized: false },
    });
  }
  return global.__hanzibitPool;
}

async function resetPool(): Promise<void> {
  // Keep the singleton pool instance alive. Better Auth captures `getPool()`
  // at module initialization time, so replacing the pool object here would
  // leave auth holding a permanently ended/stale pool reference.
  global.__hanzibitSchemaInit = undefined;
  global.__hanzibitSchemaVersion = undefined;
}

function isRetryableConnectionError(error: unknown): boolean {
  if (!error || typeof error !== "object") return false;

  const code = "code" in error ? String(error.code) : "";
  const message = "message" in error ? String(error.message) : "";

  return (
    code === "ECONNRESET" ||
    code === "57P01" ||
    code === "57P02" ||
    code === "57P03" ||
    code === "53300" ||
    message.includes("ECONNRESET") ||
    message.includes("Connection terminated unexpectedly")
  );
}

async function runWithReconnect<T>(fn: () => Promise<T>): Promise<T> {
  try {
    return await fn();
  } catch (error) {
    if (!isRetryableConnectionError(error)) {
      throw error;
    }

    await resetPool();
    await ensureAppSchema();
    return fn();
  }
}

async function initializeSchema(): Promise<void> {
  const pool = getPool();
  await pool.query(APP_SCHEMA_SQL);
  await pool.query(`
    DO $$
    DECLARE
      email_verified_type TEXT;
    BEGIN
      SELECT data_type
      INTO email_verified_type
      FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name = 'user'
        AND column_name = 'emailVerified';

      IF email_verified_type IS NOT NULL AND email_verified_type <> 'boolean' THEN
        ALTER TABLE "user"
          ALTER COLUMN "emailVerified" DROP DEFAULT;

        ALTER TABLE "user"
          ALTER COLUMN "emailVerified"
          TYPE BOOLEAN
          USING CASE
            WHEN COALESCE("emailVerified"::text, '0') IN ('1', 'true', 't', 'TRUE', 'T') THEN TRUE
            ELSE FALSE
          END;

        ALTER TABLE "user"
          ALTER COLUMN "emailVerified" SET DEFAULT FALSE;
      END IF;
    END $$;
  `);
  await pool.query(`
    ALTER TABLE teacher_strategies
      ADD COLUMN IF NOT EXISTS refinement_note TEXT,
      ADD COLUMN IF NOT EXISTS last_refined_at TIMESTAMPTZ
  `);
  await pool.query(`
    ALTER TABLE assignments
      ADD COLUMN IF NOT EXISTS template_id TEXT
  `);
  await pool.query(`
    ALTER TABLE classrooms
      ADD COLUMN IF NOT EXISTS is_private_tutoring INTEGER NOT NULL DEFAULT 0
  `);
  await pool.query(`
    ALTER TABLE journal_entries
      ADD COLUMN IF NOT EXISTS source_type TEXT,
      ADD COLUMN IF NOT EXISTS source_ref TEXT,
      ADD COLUMN IF NOT EXISTS source_prompt TEXT
  `);
  await pool.query(`
    ALTER TABLE teacher_inquiries
      ADD COLUMN IF NOT EXISTS onboarding_message TEXT,
      ADD COLUMN IF NOT EXISTS initial_assignment_id TEXT,
      ADD COLUMN IF NOT EXISTS conversion_completed_at TIMESTAMPTZ
  `);
  await pool.query(`
    ALTER TABLE teacher_tutoring_settings
      ADD COLUMN IF NOT EXISTS cadence_type TEXT,
      ADD COLUMN IF NOT EXISTS target_session_length_minutes INTEGER,
      ADD COLUMN IF NOT EXISTS cadence_notes TEXT
  `);
  await pool.query(`
    ALTER TABLE private_student_goals
      ADD COLUMN IF NOT EXISTS progress_status TEXT,
      ADD COLUMN IF NOT EXISTS progress_note TEXT,
      ADD COLUMN IF NOT EXISTS last_progress_at TIMESTAMPTZ
  `);
  await pool.query(`
    ALTER TABLE private_lesson_history
      ADD COLUMN IF NOT EXISTS issue_tags_json TEXT NOT NULL DEFAULT '[]',
      ADD COLUMN IF NOT EXISTS intervention_note TEXT
  `);
  await pool.query(`
    ALTER TABLE private_students
      ADD COLUMN IF NOT EXISTS last_strategy_id TEXT REFERENCES teacher_strategies(id) ON DELETE SET NULL,
      ADD COLUMN IF NOT EXISTS last_strategy_applied_at TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS last_playbook_id TEXT REFERENCES teacher_playbooks(id) ON DELETE SET NULL,
      ADD COLUMN IF NOT EXISTS last_playbook_applied_at TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS last_review_snapshot_at TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS last_plan_adapted_at TIMESTAMPTZ
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS teacher_playbooks (
      id TEXT PRIMARY KEY,
      teacher_user_id TEXT NOT NULL,
      title TEXT NOT NULL,
      summary TEXT NOT NULL,
      issue_focus TEXT,
      goal_focus TEXT,
      when_to_use TEXT,
      guidance TEXT,
      linked_template_id TEXT REFERENCES assignment_templates(id) ON DELETE SET NULL,
      linked_resource_id TEXT REFERENCES teacher_resources(id) ON DELETE SET NULL,
      refinement_note TEXT,
      last_refined_at TIMESTAMPTZ,
      replacement_playbook_id TEXT REFERENCES teacher_playbooks(id) ON DELETE SET NULL,
      usage_count INTEGER NOT NULL DEFAULT 0,
      archived INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    ALTER TABLE teacher_playbooks
      ADD COLUMN IF NOT EXISTS refinement_note TEXT,
      ADD COLUMN IF NOT EXISTS last_refined_at TIMESTAMPTZ,
      ADD COLUMN IF NOT EXISTS replacement_playbook_id TEXT REFERENCES teacher_playbooks(id) ON DELETE SET NULL
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_teacher_playbooks_teacher
      ON teacher_playbooks(teacher_user_id, created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_teacher_playbooks_focus
      ON teacher_playbooks(teacher_user_id, archived, updated_at DESC)
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS teacher_playbook_strategies (
      id TEXT PRIMARY KEY,
      playbook_id TEXT NOT NULL REFERENCES teacher_playbooks(id) ON DELETE CASCADE,
      strategy_id TEXT NOT NULL REFERENCES teacher_strategies(id) ON DELETE CASCADE,
      sort_order INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE(playbook_id, strategy_id)
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_teacher_playbook_strategies_playbook
      ON teacher_playbook_strategies(playbook_id, sort_order, created_at)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_teacher_playbook_strategies_strategy
      ON teacher_playbook_strategies(strategy_id, created_at)
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS private_student_playbook_applications (
      id TEXT PRIMARY KEY,
      private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
      playbook_id TEXT NOT NULL REFERENCES teacher_playbooks(id) ON DELETE CASCADE,
      applied_by_user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      application_note TEXT,
      linked_review_id TEXT REFERENCES private_student_reviews(id) ON DELETE SET NULL,
      linked_lesson_plan_id TEXT REFERENCES private_lesson_plans(id) ON DELETE SET NULL,
      linked_goal_id TEXT REFERENCES private_student_goals(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_private_playbook_apps_private
      ON private_student_playbook_applications(private_student_id, applied_at DESC, created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_private_playbook_apps_playbook
      ON private_student_playbook_applications(playbook_id, applied_at DESC, created_at DESC)
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS private_student_playbook_outcomes (
      id TEXT PRIMARY KEY,
      playbook_application_id TEXT NOT NULL UNIQUE REFERENCES private_student_playbook_applications(id) ON DELETE CASCADE,
      private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
      teacher_playbook_id TEXT NOT NULL REFERENCES teacher_playbooks(id) ON DELETE CASCADE,
      teacher_user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      outcome_status TEXT NOT NULL CHECK(outcome_status IN ('helped', 'partial', 'no_change', 'replace')),
      outcome_note TEXT,
      recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_private_playbook_outcomes_private
      ON private_student_playbook_outcomes(private_student_id, recorded_at DESC, created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_private_playbook_outcomes_playbook
      ON private_student_playbook_outcomes(teacher_playbook_id, recorded_at DESC, created_at DESC)
  `);
  await pool.query(`
    ALTER TABLE daily_loop_completions
      ADD COLUMN IF NOT EXISTS review_completed INTEGER NOT NULL DEFAULT 0,
      ADD COLUMN IF NOT EXISTS study_completed INTEGER NOT NULL DEFAULT 0,
      ADD COLUMN IF NOT EXISTS write_completed INTEGER NOT NULL DEFAULT 0
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_assignments_template
      ON assignments(template_id)
  `);
  await pool.query(`
    ALTER TABLE referral_commissions
      ADD COLUMN IF NOT EXISTS payout_id TEXT
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_referral_commissions_payout
      ON referral_commissions(payout_id)
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS private_student_strategy_applications (
      id TEXT PRIMARY KEY,
      private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
      teacher_strategy_id TEXT NOT NULL REFERENCES teacher_strategies(id) ON DELETE CASCADE,
      applied_by_user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      application_note TEXT,
      linked_review_id TEXT REFERENCES private_student_reviews(id) ON DELETE SET NULL,
      linked_lesson_plan_id TEXT REFERENCES private_lesson_plans(id) ON DELETE SET NULL,
      linked_goal_id TEXT REFERENCES private_student_goals(id) ON DELETE SET NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_private_strategy_apps_private
      ON private_student_strategy_applications(private_student_id, applied_at DESC, created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_private_strategy_apps_strategy
      ON private_student_strategy_applications(teacher_strategy_id, applied_at DESC, created_at DESC)
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS private_student_strategy_outcomes (
      id TEXT PRIMARY KEY,
      strategy_application_id TEXT NOT NULL UNIQUE REFERENCES private_student_strategy_applications(id) ON DELETE CASCADE,
      private_student_id TEXT NOT NULL REFERENCES private_students(id) ON DELETE CASCADE,
      teacher_strategy_id TEXT NOT NULL REFERENCES teacher_strategies(id) ON DELETE CASCADE,
      teacher_user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
      outcome_status TEXT NOT NULL CHECK(outcome_status IN ('helped', 'partial', 'no_change', 'replace')),
      outcome_note TEXT,
      recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_private_strategy_outcomes_private
      ON private_student_strategy_outcomes(private_student_id, recorded_at DESC, created_at DESC)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_private_strategy_outcomes_strategy
      ON private_student_strategy_outcomes(teacher_strategy_id, recorded_at DESC, created_at DESC)
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS tts_cache (
      cache_key  TEXT PRIMARY KEY,
      blob_url   TEXT NOT NULL,
      char_count INTEGER NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      play_count INTEGER NOT NULL DEFAULT 0
    )
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS tts_usage (
      id            TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
      user_id       TEXT REFERENCES "user"(id) ON DELETE SET NULL,
      cache_key     TEXT,
      was_cache_hit BOOLEAN NOT NULL,
      char_count    INTEGER NOT NULL,
      type          TEXT NOT NULL CHECK (type IN ('word','sentence','dynamic')),
      created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_tts_usage_user_id ON tts_usage(user_id)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_tts_usage_created_at ON tts_usage(created_at)
  `);

  await pool.query(`
    ALTER TABLE hsk_words
      ADD COLUMN IF NOT EXISTS register TEXT NOT NULL DEFAULT 'neutral',
      ADD COLUMN IF NOT EXISTS cultural_note TEXT
  `);

  // Seed register and cultural_note values (idempotent — only updates when data differs)
  for (const item of REGISTER_SEED) {
    if (item.register && item.cultural_note) {
      await pool.query(
        `UPDATE hsk_words SET register = $1, cultural_note = $2 WHERE simplified = $3`,
        [item.register, item.cultural_note, item.simplified]
      );
    } else if (item.register) {
      await pool.query(
        `UPDATE hsk_words SET register = $1 WHERE simplified = $2`,
        [item.register, item.simplified]
      );
    } else if (item.cultural_note) {
      await pool.query(
        `UPDATE hsk_words SET cultural_note = $1 WHERE simplified = $2`,
        [item.cultural_note, item.simplified]
      );
    }
  }

  // Seed curated grammar points (idempotent via ON CONFLICT DO NOTHING)
  for (const point of CURATED_GRAMMAR_POINTS) {
    await pool.query(
      `INSERT INTO curated_grammar_points
         (hsk_level, display_order, title, pattern, explanation, examples,
          reading_passage, comprehension_question, journal_prompt)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
       ON CONFLICT (hsk_level, display_order) DO NOTHING`,
      [
        point.hsk_level,
        point.display_order,
        point.title,
        point.pattern,
        point.explanation,
        point.examples,
        point.reading_passage,
        point.comprehension_question,
        point.journal_prompt,
      ]
    );
  }

  // Seed collocations (idempotent — skip if already exists for this word+sentence pair)
  for (const item of COLLOCATION_SEED) {
    await pool.query(
      `INSERT INTO hsk_collocations (word_simplified, sentence_zh, sentence_en, known_words)
       VALUES ($1, $2, $3, $4)
       ON CONFLICT (word_simplified, sentence_zh) DO NOTHING`,
      [item.word_simplified, item.sentence_zh, item.sentence_en, item.known_words]
    );
  }

  // Seed character component breakdowns (idempotent via ON CONFLICT DO NOTHING)
  for (const item of CHARACTER_BREAKDOWN_SEED) {
    await pool.query(
      `INSERT INTO character_components (character, radical, radical_meaning, components_json, mnemonic)
       VALUES ($1, $2, $3, $4, $5)
       ON CONFLICT (character) DO NOTHING`,
      [
        item.character,
        item.radical,
        item.radical_meaning,
        JSON.stringify(item.components),
        item.mnemonic ?? null,
      ]
    );
  }
}

export async function ensureAppSchema(): Promise<void> {
  if (!global.__hanzibitSchemaInit || global.__hanzibitSchemaVersion !== SCHEMA_VERSION) {
    global.__hanzibitSchemaInit = initializeSchema();
    global.__hanzibitSchemaVersion = SCHEMA_VERSION;
  }
  await global.__hanzibitSchemaInit;
}

export async function query<T extends QueryResultRow>(
  text: string,
  params: unknown[] = []
): Promise<T[]> {
  await ensureAppSchema();
  const result = await runWithReconnect(() => getPool().query<T>(text, params));
  return result.rows;
}

export async function queryOne<T extends QueryResultRow>(
  text: string,
  params: unknown[] = []
): Promise<T | undefined> {
  const rows = await query<T>(text, params);
  return rows[0];
}

export async function execute(text: string, params: unknown[] = []): Promise<void> {
  await ensureAppSchema();
  await runWithReconnect(() => getPool().query(text, params));
}

export async function withTransaction<T>(
  fn: (client: PoolClient) => Promise<T>
): Promise<T> {
  await ensureAppSchema();
  const client = await getPool().connect();
  try {
    await client.query("BEGIN");
    const result = await fn(client);
    await client.query("COMMIT");
    return result;
  } catch (error) {
    await client.query("ROLLBACK");
    throw error;
  } finally {
    client.release();
  }
}

export { APP_SCHEMA_SQL };
